title: mehlinger.me
email: tmehlinger@gmail.com
description: I discuss Python, technology, and being a good citizen.
baseurl: ""
url: "https://mehlinger.me"
twitter_username: maber
github_username:  tmehlinger
linkedin_username:  mehlinger

markdown: kramdown
kramdown:
  parse_block_html: true
paginate: 10
paginate_path: "/blog/:num"
gems:
  - jekyll-paginate
